# Build Stage
FROM golang:1.24-alpine AS builder
WORKDIR /app
RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download
COPY . .

# HTTPサーバー
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-s -w" -o app-http ./cmd/http

# Runtime Stage
FROM alpine:3.19
WORKDIR /app
RUN apk add --no-cache iproute2
COPY --from=builder /app/app-http .
EXPOSE 8080

ENTRYPOINT [ "/app/app-http" ]