# Build Stage
FROM golang:1.24-alpine AS builder
WORKDIR /app
RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download
COPY . .

# HTTPサーバー
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-s -w" -o app-worker ./cmd/worker

# Runtime Stage
FROM alpine:3.19

RUN apk add --no-cache ffmpeg

WORKDIR /app
COPY --from=builder /app/app-worker .

USER nobody

ENTRYPOINT [ "/app/app-worker" ]