// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"example.com/m/internal/infrastructure/persistence/postgres"
	"example.com/m/internal/infrastructure/persistence/postgres/outbox"
	"example.com/m/internal/infrastructure/persistence/postgres/user"
	"example.com/m/internal/infrastructure/persistence/postgres/video"
	"example.com/m/internal/infrastructure/storage/s3"
	"example.com/m/internal/infrastructure/transcoder/ffmpeg"
	"example.com/m/internal/interface/http"
	user3 "example.com/m/internal/interface/http/user"
	"example.com/m/internal/interface/http/video/manager"
	"example.com/m/internal/interface/http/video/viewer"
	user2 "example.com/m/internal/usecase/user"
	"example.com/m/internal/usecase/video/manage"
	"example.com/m/internal/usecase/video/view"
	"github.com/jmoiron/sqlx"
	"github.com/labstack/echo/v4"
)

// Injectors from wire.go:

func InitializeHTTPServer() (*HTTPServerApp, error) {
	config := postgres.NewPostgresConfig()
	db, err := postgres.NewClient(config)
	if err != nil {
		return nil, err
	}
	repository := user.NewRepository(db)
	context := provideContext()
	s3Config := s3.NewS3Config()
	s3ClientSet, err := s3.NewClient(context, s3Config)
	if err != nil {
		return nil, err
	}
	iconStorage := s3.NewIconStorage(s3ClientSet, s3Config)
	userUseCaseInterface := user2.NewUserUseCase(repository, iconStorage)
	handler := user3.NewHandler(userUseCaseInterface)
	videoRepository := video.NewRepository(db)
	outboxRepository := outbox.NewRepository(db)
	storage := s3.NewVideoStorage(s3ClientSet, s3Config)
	transcoder := ffmpeg.NewFFmpegTranscoder(storage)
	unitOfWork := postgres.NewTransactor(db)
	videoManagementUseCaseInterface := manage.NewVideoManagementUseCase(videoRepository, outboxRepository, storage, transcoder, unitOfWork)
	videoManagementHandler := manager.NewVideoManagementHandler(videoManagementUseCaseInterface)
	videoViewingUseCaseInterface := view.NewVideoViewingUseCase(videoRepository, storage)
	videoViewingHandler := viewer.NewVideoViewingHandler(videoViewingUseCaseInterface)
	echo := http.NewRouter(handler, videoManagementHandler, videoViewingHandler)
	httpServerApp := &HTTPServerApp{
		Echo: echo,
		DB:   db,
	}
	return httpServerApp, nil
}

// wire.go:

type HTTPServerApp struct {
	Echo *echo.Echo
	DB   *sqlx.DB
}

func provideContext() context.Context {
	return context.Background()
}
